FROM node:alpine AS build

WORKDIR /app

COPY former/front/package.json former/front/package-lock.json ./
RUN npm install

COPY former/front .
RUN npm run build

FROM nginx:alpine

COPY former/front/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]