FROM node:20-alpine
WORKDIR /app

COPY former/front/package.json former/front/package-lock.json* ./
RUN npm install

COPY former/front ..
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]