FROM node:20-alpine AS build

WORKDIR /app

COPY former/front/package.json former/front/package-lock.json ./
RUN npm install

COPY former/front .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]